// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CaptureApp.iOS
{
	public partial class RootTabViewController : UITabBarController
	{
		
		public RootTabViewController (IntPtr handle) : base (handle)
		{
			this.Title = "Capture";
		}


		public override void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear (animated);
			if (!AppDelegate.MomentsManager.AccountManager.LoggedIn) {
				LoginViewController loginViewController = new LoginViewController ();
				this.NavigationController.PresentViewController (loginViewController, true, null);
			}

		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			this.TabBar.TintColor = this.NavigationController.NavigationBar.TintColor;
			this.NavigationController.Toolbar.TintColor = this.NavigationController.NavigationBar.TintColor;
		}
	}
}
